#!/usr/bin/python

import FASTAparser as FA

def reverseDNA(DNA):
	intab ="ATCG"
	outtab ="TAGC"
	
	return DNA.translate({ord(x): y for (x,y) in zip(intab,outtab)})[::-1]

def reverse_palindrome_check(n,string):
	position=[]
	for i in range(0, len(string)-n+1):	
		tempstring = string[i:i+n]
		rtemp = reverseDNA(tempstring)
		if tempstring == rtemp:
			position.append(i+1)

	return position

def main():

	DNAstring = FA.FASTA('data/rosalind_revp.txt')

	string = DNAstring.values()
	DNA = str(string)
	
	result = {}
	for number in range(4,13):
		result[str(number)] = reverse_palindrome_check(number, DNA)

	for key in result.keys():
		if result[key] != []:
			for item in result[key]:
				print (str(item) + ' ' + str(key))

	print(DNA)
	print (len('ATATGTGGTACACCTAATGTCATAGTCCATACGACGTAACCTATTCGTCTAATCAAGCCGGATGACTGTTGCGAGCCGCCGACACAGTACCGTACTACTCCACACAGGGGTTTGGGCGGAATGCCTCGAAACCCCTTTGAGATTCTGTTTCCACTTCCATTTAGTGTAGCTGTAGTATCAACCTGCGCCCAGTGAGTGCTGGATTGGATACCAGCGCACTATGGCAAAAAGTACAGATCCAAGTGTGAGCTCCTATATACCTTCGACCCATGAACTCCTGGTATTCAATTAGAGGTCGCTCTGGAGCAAAGCCAATTCAGAGACAGTTAAAAAAGATACCCTGCTGGTAGATTTTGGCCGCCGATATCTTCGACTCAACGACGGAGGATTATTTAAAAATGCCGCTAAGTTTACTGCATCACCCAGTTTAGCGAATGGTTATTGAAGGTAGGCCATGTGCGACACATTTACGACTCACTTAAACATGGTACAATTACGTAATTTTTGAGGATCGACTAAGGCGCACTCAAAGTGGGCACACCTTCCGTCGAACCCTGTTAGTCCGGGGTTTTACAGCGCTTTTCAGTGTCAGGGTCCATACCGACCGTAAGGTAGTAGGCGAGGTTAGTATTTATACCCGGTGTCGCGGAACTTAGTACTACCCCGTCGTCGAGGAAGGACCAATCACCGCACGCGACGACTGACAGCTAGGTGCTAGTTTCTTCTGTTATCATGTGGTGTTATCTGGCACTTGAGACCACATATCAGTTAATACACCAACCCCTAATTCCTAGTGTATTGCTGCTTTCCCAGTCTAAACATAGATAACCCCCACTCTGCTGTTCCAGGGCGACACATGGAGTTCTACTATCGCCGTCGTACATCTTCTGCAATTGGATACCTCTGAAGGGAGCCCTACACCAACTGCGGTATCCCTAATGCGTAGTCCCCTCAGCGCTAGCTGTGTGTAAAAGTTCTTTATAGCGCACCGCGC'))
	print (len(DNA))



if __name__ == '__main__':
	main()
